### ISSUE TITLE
Multi-stage training  vs  end-to-end training?

### ISSUE THREAD

**Issue by Amygyx** [Nikolai10/MRIC#5]
I appreciate the work and effort you’ve put into this project. 
I have a question regarding the training strategy. I noticed that you employed a multi-stage training approach instead of an end-to-end method from scratch. I’m curious if you’ve tried implementing end-to-end training from scratch during your experiments? If so, how did it perform?

I look forward to your response.

**Comment by Nikolai10** [comment]
Hello @Amygyx,

thanks for your interest.

As far as I remember, end-to-end training from scratch led to instabilities (and therefore poor results), which is why I switched to the two-stage learning objective. 

By instability, I mean that the loss did not converge properly and sudden “jumps” occurred, resulting in poor gradients that seemed to slow down training progress.

In theory, everything seems simple - but in practice, these systems require quite some tuning and engineering. Hope this provides some insight!

**Comment by Amygyx** [comment]
Thank you for the quick reply, it was helpful. Much appreciated!
